[general]
import = [
    "~/.config/alacritty/themes/citylights.toml"
]

[terminal.shell]
# Example
program = "/usr/bin/bash"
args = ["-l"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold" }
size = 12.0
