[general]
import = [
    "~/.config/alacritty/themes/citylights.toml"
]

[window]
dimensions = { columns = 200, lines = 40 }
padding = { x = 5, y = 5 }

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold" }
size = 12.0
