[general]
import = [
    "~/.config/alacritty/themes/citylights.toml"
]

[window]
padding = { x = 10, y = 5 }
startup_mode = "Maximized"
opacity = 0.9

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold" }
size = 12.0
