name: Installation test via chezmoi
on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  installation-on-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove pre-installed apps
        run: |
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get clean
          sudo apt-get autoremove
      - name: Install chezmoi
        run: sh -c "$(wget -qO- get.chezmoi.io)" -- -b $HOME/.local/bin
      - name: Show home directory before appling
        run: ls -la $HOME
      - name: Apply dotfiles
        run: chezmoi init --apply --branch ${{ github.ref_name }} $GITHUB_REPOSITORY_OWNER
      - name: Show source directory of dotfiles
        run : ls -la $(chezmoi source-path)
      - name: Show home directory after appling
        run: ls -la $HOME
      - name: Show .zshenv and .zshrc
        run: |
          echo "===== .zshenv ====="
          cat $HOME/.zshenv
          echo "===== .zshrc ====="
          cat $HOME/.zshrc
      - name: Show PATH in zsh
        run: zsh -c "echo \"$PATH\""
      - name: Check if GUI apps are installed
        run: |
          type google-chrome
          type code
          type alacritty
      - name: Check if CUI tools are installed
        run: |
          type docker
          type starship
      - name: Show AWS CLI version
        run: aws --version
