name: Installation test via chezmoi
on:
  push:
    branches:
      - "feature/**"
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  installation-on-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Install chezmoi
        run: sh -c "$(wget -qO- get.chezmoi.io)" -- -b $HOME/.local/bin
      - name: Show home directory before appling
        run: ls -la $HOME
      - name: Apply dotfiles
        run: chezmoi init --apply --branch ${{ github.ref_name }} $GITHUB_REPOSITORY_OWNER
      - name: Show source directory of dotfiles
        run : ls -la $(chezmoi source-path)
      - name: Show home directory after appling
        run: ls -la $HOME
      - name: Check if zsh is installed
        run: zsh -c "echo zsh has been successfully installed."
      - name: Check if GUI apps are installed
        run: |
          type google-chrome
          type code
          type alacritty
      - name: Test Docker installation
        run: |
          zsh -c ". $(chezmoi source-path)/run_once_install_docker.sh && _install_docker"
